#!/usr/bin/env python3
"""Build from the exact user-provided PKG, preserving its runtime/assets."""
import argparse
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
from patch import PKG_SHA, INPUT_SHA, sha, build_hooks, patch

ROOT = Path(__file__).resolve().parent.parent
CONTENT = 'IV0000-BREW13533_00-TROPHYV12UI01200'
NAME = 'Trophy_Unlocker_13.52_V13_6_4_TEST.pkg'


def run(args, cwd, log=None):
    p = subprocess.run(list(map(str, args)), cwd=cwd, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True)
    if log: log.write_text(p.stdout)
    if 'Error:' in p.stdout or '[FAIL]' in p.stdout or '[ERROR]' in p.stdout:
        raise RuntimeError(p.stdout)
    return p.stdout


def sfo_update(data):
    b = bytearray(data)
    magic, ver, keys, values, count = struct.unpack_from('<5I', b)
    assert magic == 0x46535000 and ver == 0x101
    desired = {'APP_VER': '01.11', 'VERSION': '01.11',
               'TITLE': 'Trophy Unlocker 13.52 V13.6.4 TEST'}
    found = {}
    for i in range(count):
        at = 20+16*i
        key, kind, size, cap, off = struct.unpack_from('<HHIII', b, at)
        name = bytes(b[keys+key:b.index(0, keys+key)]).decode()
        if name in desired:
            value = desired[name].encode()+b'\0'
            assert kind == 0x204 and len(value) <= cap
            b[values+off:values+off+cap] = value+bytes(cap-len(value))
            struct.pack_into('<I', b, at+4, len(value))
        value = bytes(b[values+off:values+off+cap]).rstrip(b'\0')
        found[name] = value.decode() if kind == 0x204 else value.hex()
    assert all(found[k] == v for k, v in desired.items())
    assert found['TITLE_ID'] == 'BREW13533' and found['CONTENT_ID'] == CONTENT
    return bytes(b), found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input_pkg', type=Path)
    ap.add_argument('--sdk', type=Path, default=os.environ.get('OO_PS4_TOOLCHAIN'))
    args = ap.parse_args()
    if args.sdk is None: ap.error('set OO_PS4_TOOLCHAIN or --sdk')
    tool = args.sdk.resolve()/'bin/linux/PkgTool.Core'
    gp4tool = args.sdk.resolve()/'bin/linux/create-gp4'
    pkg = args.input_pkg.resolve()
    b = pkg.read_bytes()
    assert sha(b) == PKG_SHA, 'Input must be the exact user-provided V13.6.3 PKG'
    work, dist = ROOT/'build_v1364', ROOT/'dist_v1364'
    work.mkdir(exist_ok=True); dist.mkdir(exist_ok=True)
    extracted = work/'original'
    if not (extracted/'uroot/eboot.bin').exists():
        run([tool, 'pkg_extract', pkg, extracted], ROOT, work/'original-extract.log')
    original = extracted/'uroot'
    assert sha((original/'eboot.bin').read_bytes()) == INPUT_SHA
    expected = {'eboot.bin', 'sce_sys/keystone', 'sce_sys/about/right.sprx',
                'sce_module/libc.prx', 'sce_module/libSceFios2.prx',
                'assets/fonts/Bebas-Regular.ttf', 'assets/fonts/VeraMono.ttf',
                'assets/images/enemy.tga', 'assets/images/player.tga', 'assets/images/projectile.tga'}
    assert {str(p.relative_to(original)) for p in original.rglob('*') if p.is_file()} == expected
    app = work/'app'
    if app.exists(): shutil.rmtree(app)
    shutil.copytree(original, app)
    # Unencrypted PARAM_SFO and ICON0 entries; these offsets/sizes are protected
    # by the full package digest above, not used for arbitrary input packages.
    sfo, values = sfo_update(b[0x3910:0x3910+0x434])
    (app/'sce_sys/param.sfo').write_bytes(sfo)
    (app/'sce_sys/icon0.png').write_bytes(b[0x5d50:0x5d50+0x13e78])
    payload, symbols = build_hooks(work/'hooks')
    changed, report = patch((original/'eboot.bin').read_bytes(), payload, symbols)
    (app/'eboot.bin').write_bytes(changed)
    (work/'hooks/patch-report.json').write_text(json.dumps(report, indent=2)+'\n')
    test = run([sys.executable, ROOT/'v1364/test_hooks.py', work/'hooks', original/'eboot.bin'], ROOT,
               dist/'host-tests.txt')
    print(test, end='')
    # keystone is generated by PkgTool from the existing content ID/passcode.
    inputs = sorted(str(p.relative_to(app)) for p in app.rglob('*')
                    if p.is_file() and p.name != 'keystone')
    run([gp4tool, '-out', 'pkg.gp4', '--content-id='+CONTENT, '--files', ' '.join(inputs)], app)
    run([tool, 'pkg_build', 'pkg.gp4', '.'], app, work/'pkg-build.log')
    built = app/(CONTENT+'.pkg')
    validation = run([tool, 'pkg_validate', '--verbose', built], app, dist/'pkg-validation.txt')
    assert sum(line.startswith('[OK]') for line in validation.splitlines()) == 28, validation
    print('PASS: 28 package integrity checks')
    roundtrip = work/'roundtrip'
    if roundtrip.exists(): shutil.rmtree(roundtrip)
    run([tool, 'pkg_extract', built, roundtrip], ROOT, work/'roundtrip.log')
    actual = roundtrip/'uroot'
    assert {str(p.relative_to(actual)) for p in actual.rglob('*') if p.is_file()} == expected
    manifest = {}
    for rel in sorted(expected):
        a, out = (app/rel).read_bytes(), (actual/rel).read_bytes()
        assert a == out, 'Roundtrip mismatch: '+rel
        if rel != 'eboot.bin': assert out == (original/rel).read_bytes(), rel
        manifest[rel] = sha(out)
    # Read special entries by their displayed entry indexes, not PS4 entry IDs.
    run([tool, 'pkg_extractentry', built, '9', work/'roundtrip-param.sfo'], ROOT)
    _, rt_values = sfo_update((work/'roundtrip-param.sfo').read_bytes())
    # Separate raw assertions avoid masking an incorrect packaged SFO.
    raw = (work/'roundtrip-param.sfo').read_bytes()
    for value in ['01.11', 'Trophy Unlocker 13.52 V13.6.4 TEST', 'BREW13533', CONTENT]:
        assert value.encode()+b'\0' in raw
    run([tool, 'pkg_extractentry', built, '13', work/'roundtrip-icon.png'], ROOT)
    assert (work/'roundtrip-icon.png').read_bytes() == (app/'sce_sys/icon0.png').read_bytes()
    shutil.copyfile(built, dist/NAME)
    (dist/'SHA256SUMS.txt').write_text(sha((dist/NAME).read_bytes())+'  '+NAME+'\n')
    (dist/'validation.json').write_text(json.dumps(dict(
        pkg_sha256=sha((dist/NAME).read_bytes()), files=manifest, sfo=rt_values,
        patch=report, package_checks=28, host_test_methods=8, hardware_tested=False), indent=2)+'\n')
    print('PASS: extracted eboot/runtime/assets/keystone match; SFO and icon verified')
    print(dist/NAME)


if __name__ == '__main__': main()
